// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var nbpApiBaseUrl = "http://api.nbp.pl/api/exchangerates/rates/a";

var baseCurrency = "PLN";

exports.nbpApiBaseUrl = nbpApiBaseUrl;
exports.baseCurrency = baseCurrency;
/* No side effect */
