// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function actionToString(action) {
  switch (action) {
    case /* Remove */0 :
        return "remove";
    case /* MoveUp */1 :
        return "move up";
    case /* MoveDown */2 :
        return "move down";
    
  }
}

exports.actionToString = actionToString;
/* No side effect */
