// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function CurrenciesComponent(Props) {
  var currencies = Props.currencies;
  var onSelectCurrency = Props.onSelectCurrency;
  return React.createElement("select", {
              onChange: (function (e) {
                  return Curry._1(onSelectCurrency, e.target.value);
                })
            }, Belt_List.toArray(Belt_List.map(currencies, (function (c) {
                        return React.createElement("option", {
                                    key: c[/* currencyCode */0],
                                    value: c[/* currencyCode */0]
                                  }, c[/* currencyCode */0] + ("-" + c[/* currencyDescription */1]));
                      }))));
}

var make = CurrenciesComponent;

exports.make = make;
/* react Not a pure module */
