// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var apiBaseUrl = "http://api.nbp.pl/api/exchangerates/rates/a";

function url(currencyCode) {
  return "" + (String(apiBaseUrl) + ("/" + (String(currencyCode) + "/")));
}

function exchangeRateItemDecoder(json) {
  return /* record */[
          /* no */Json_decode.field("no", Json_decode.string, json),
          /* effectiveDate */Json_decode.field("effectiveDate", Json_decode.string, json),
          /* mid */Json_decode.field("mid", Json_decode.$$float, json)
        ];
}

function exchangeRateDecoder(json) {
  return /* record */[
          /* table */Json_decode.field("table", Json_decode.string, json),
          /* currency */Json_decode.field("currency", Json_decode.string, json),
          /* code */Json_decode.field("code", Json_decode.string, json),
          /* rates */Json_decode.field("rates", (function (param) {
                  return Json_decode.array(exchangeRateItemDecoder, param);
                }), json)
        ];
}

var JsonDecode = {
  exchangeRateItemDecoder: exchangeRateItemDecoder,
  exchangeRateDecoder: exchangeRateDecoder
};

function jsonToCurrencyExchangeModel(json) {
  var match = Belt_List.fromArray(json[/* rates */3]);
  if (match) {
    var head = match[0];
    return /* record */[
            /* currencyCode */json[/* code */2],
            /* exchangeRate */head[/* mid */2],
            /* date */head[/* effectiveDate */1]
          ];
  }
  
}

function jsonToCurrencyExchangeModel2(json) {
  return /* record */[
          /* currencyCode */json[/* code */2],
          /* exchangeRate */2.33,
          /* date */"222"
        ];
}

var Dto = {
  jsonToCurrencyExchangeModel: jsonToCurrencyExchangeModel,
  jsonToCurrencyExchangeModel2: jsonToCurrencyExchangeModel2
};

function fetchData(currencyCode) {
  fetch(url(currencyCode)).then((function (prim) {
            return prim.json();
          })).then((function (json) {
          var transformed = exchangeRateDecoder(json);
          console.log(jsonToCurrencyExchangeModel(transformed));
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

exports.apiBaseUrl = apiBaseUrl;
exports.url = url;
exports.JsonDecode = JsonDecode;
exports.Dto = Dto;
exports.fetchData = fetchData;
/* No side effect */
