// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ExchangeData$ReactHooksTemplate = require("./ExchangeData.bs.js");
var ListItemsModels$ReactHooksTemplate = require("./ListItemsModels.bs.js");
var ListItemsComponent$ReactHooksTemplate = require("./ListItemsComponent.bs.js");

ExchangeData$ReactHooksTemplate.fetchData("CHF");

ReactDOMRe.renderToElementWithId(React.createElement(ListItemsComponent$ReactHooksTemplate.make, {
          items: ListItemsModels$ReactHooksTemplate.sampleCurrencies
        }), "exchangeRatesList");

/*  Not a pure module */
