// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ListItemsModels$ReactHooksTemplate = require("./ListItemsModels.bs.js");

function reduced(item) {
  return Belt_List.reduce(item[/* actions */2], "", (function (acc, el) {
                return acc + ("; " + ListItemsModels$ReactHooksTemplate.actionToString(el));
              }));
}

function ListItemComponent(Props) {
  var item = Props.item;
  return React.createElement("div", {
              key: item[/* id */0]
            }, item[/* caption */1], " ", reduced(item));
}

var make = ListItemComponent;

exports.reduced = reduced;
exports.make = make;
/* react Not a pure module */
