// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ListItemComponent$ReactHooksTemplate = require("./ListItemComponent.bs.js");

function renderList(items) {
  if (items !== undefined) {
    var theList = Belt_List.map(items, (function (item) {
            return React.createElement(ListItemComponent$ReactHooksTemplate.make, {
                        item: item
                      });
          }));
    return React.createElement("div", undefined, Belt_List.toArray(theList));
  } else {
    return React.createElement("div", undefined);
  }
}

function ListItemsComponent(Props) {
  return renderList(Props.items);
}

var make = ListItemsComponent;

exports.renderList = renderList;
exports.make = make;
/* react Not a pure module */
