// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function actionToString(action) {
  switch (action) {
    case /* Remove */0 :
        return "remove";
    case /* MoveUp */1 :
        return "move up";
    case /* MoveDown */2 :
        return "move down";
    
  }
}

var sampleCurrencies = /* :: */[
  /* record */[
    /* id */"CHF",
    /* caption */"CHF/PLN 3.35",
    /* actions : :: */[
      /* Remove */0,
      /* [] */0
    ]
  ],
  /* :: */[
    /* record */[
      /* id */"USD",
      /* caption */"USD/PLN 3.35",
      /* actions : :: */[
        /* Remove */0,
        /* :: */[
          /* MoveUp */1,
          /* :: */[
            /* MoveDown */2,
            /* [] */0
          ]
        ]
      ]
    ],
    /* :: */[
      /* record */[
        /* id */"EUR",
        /* caption */"EUR/PLN 4.21",
        /* actions : :: */[
          /* Remove */0,
          /* :: */[
            /* MoveUp */1,
            /* :: */[
              /* MoveDown */2,
              /* [] */0
            ]
          ]
        ]
      ],
      /* [] */0
    ]
  ]
];

exports.actionToString = actionToString;
exports.sampleCurrencies = sampleCurrencies;
/* No side effect */
